name: 中华人民共和国开放数据计划
timezone: Asia/Shanghai
markdown: kramdown
highlight: null
permalink: /:year-:month-:day.html

exclude:
  - README.md

nav:
  - title: 关于
    link: "/about/"
  - title: 项目
    link: "#"
  - title: 博客
    link: "#"
